// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jzolduytoolovyhxdibd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6b2xkdXl0b29sb3Z5aHhkaWJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzNzI4OTMsImV4cCI6MjA2Njk0ODg5M30.Pq_8Ruh2WXsuiO1N2PMXYwdIGfn8jrbJa4ozqXIufI4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});